DO NOT MERGE: Iiif v6 01 09 2023
scientist-softserv/actions pull request #28
Opened 2023-01-10 00:42 UTC by ShanaLMoore

2023-01-10 22:41 UTC, bkiahstroud requested changes
@ShanaLMoore I know this is marked as "DO NOT MERGE", but I actually think this could be contributed to the `main` branch if we make it just a little more dynamic. 

We're really trying to avoid having an off-shoot branch for each repo because that gets complicated really quickly. Typically, if a repo needs certain changes, our best (current) options are: 

1. Make changes to Actions `main` that don't break other repos 
2. Manually set up CI in that repo if it's just too different from Actions 

For this branch specifically, the file presence checks are good as is. Only the `rake engine_cart:generate` needs to be dynamic. I imagine the changes needed will be very similar to what I did for the rspec command. Take a look at these two PRs and let me know if you have any questions and/or want to pair on it: 

- https://github.com/scientist-softserv/actions/pull/5 
- https://github.com/scientist-softserv/ljk-brick/pull/71

2023-01-10 23:44 UTC, ShanaLMoore commented
> @ShanaLMoore I know this is marked as "DO NOT MERGE", but I actually think this could be contributed to the `main` branch if we make it just a little more dynamic.
> 
> We're really trying to avoid having an off-shoot branch for each repo because that gets complicated really quickly. Typically, if a repo needs certain changes, our best (current) options are:
> 
>     1. Make changes to Actions `main` that don't break other repos
> 
>     2. Manually set up CI in that repo if it's just too different from Actions
> 
> 
> For this branch specifically, the file presence checks are good as is. Only the `rake engine_cart:generate` needs to be dynamic. I imagine the changes needed will be very similar to what I did for the rspec command. Take a look at these two PRs and let me know if you have any questions and/or want to pair on it:
> 
>     * #5
> 
>     * [scientist-softserv/ljk-brick#71](https://github.com/scientist-softserv/ljk-brick/pull/71)

Good call, I didn't realize how close it was to being merge-able. 🙃 Thanks for your feedback. I'll update it as such.

2023-01-11 00:13 UTC, ShanaLMoore commented on .github/workflows/lint.yaml
> +          [ -f "db/schema.rb" ] && chmod 777 db/schema.rb;
checks for the existence of a file before running the chmod command against it.

2023-01-11 00:14 UTC, ShanaLMoore commented on .github/workflows/test.yaml
> +      setup_db_cmd:
dynamic variable created with a default value that most projects use. This supports iiif_print repo because it'll need a different setup command.

2023-01-11 00:14 UTC, ShanaLMoore commented on .github/workflows/test.yaml
> +          "${{ inputs.setup_db_cmd }}"
This line uses the value of the dynamic setup dc cmd variable.

2023-01-11 00:27 UTC, bkiahstroud approved these changes
Looks great, nice job!

2023-01-11 00:33 UTC, merged